#!/bin/sh

# crontabs
sed -i '/dnsmasq-extra/d' /etc/crontabs/root
echo '0 0 5 * * /etc/init.d/dnsmasq-extra update' >>/etc/crontabs/root
echo '3 7 * * * /etc/init.d/dnsmasq-extra restart' >>/etc/crontabs/root
crontab /etc/crontabs/root

# firewall.extra.include
echo "/etc/init.d/dnsmasq-extra rules" >/etc/dnsmasq-extra.d/firewall.include
uci -q batch <<-EOF >/dev/null
	delete firewall.dnsmasq_extra
	set firewall.dnsmasq_extra=include
	set firewall.dnsmasq_extra.type=script
	set firewall.dnsmasq_extra.path=/etc/dnsmasq-extra.d/firewall.include
	commit firewall
EOF

# chinadns_chnroute.txt
[ -f /etc/chinadns_chnroute.txt ] ||
	ln -sf /etc/dnsmasq-extra.d/chnroute.txt /etc/chinadns_chnroute.txt

exit 0
